### ISSUE TITLE
the translated 404.html pages are not included

### ISSUE THREAD

**Issue by yater** [cbsd/cbsd-wwwdoc#22]
at https://www.bsdstore.ru/de/screenshots.html for example the english appears.
but https://www.bsdstore.ru/de/404.html :-D is translated well. :-D :-)

**Comment by olevole** [comment]
Similar problem with other languages (ru) - I previously preferred to link to English.
Well, if the site becomes to multi-language then we just need to create a copy of screenshots.html page (for /de/ at the moment).

@yater, if you want to improve German localization, I can grant you the rights to the commit - do you wan this ;-)? Thank you very much for participating!

**Comment by olevole** [comment]
https://github.com/cbsd/cbsd-wwwdoc/commit/5c823dce67445c0eb9c81c32960e1e01aa6e6245
