### ISSUE TITLE
there is no english translation for the article bhyve_vs_jails.html

### ISSUE THREAD

**Issue by miker** [cbsd/cbsd-wwwdoc#5]
Hello,

There is no english translation for https://www.bsdstore.ru/en/articles/bhyve_vs_jails.html. The en version is nearly the same as the ru version. Please add the english translation, even if it is auto-translated like some of the other articles.

Thanks

**Comment by olevole** [comment]
Thank. For some reason there is no page ( but should ). I'll create it soon

**Comment by miker** [comment]
Awesome thanks.

**Comment by miker** [comment]
This is one I'm looking forward to doing.

**Comment by olevole** [comment]
I think this is not relevant, the article requires an update
